### ISSUE TITLE
Can't find TTS model trained with IndicVoices-R dataset 

### ISSUE THREAD

**Issue by Aalisha** [AI4Bharat/IndicVoices-R#3]
Hi,
Thank you for the great work and adding this milestone effort for Indian languages. The description mentioned that TTS model trained with IndicVoices-R dataset and code is open sourced for these 22 languages. I was wondering where can we find the TTS model trained on this new dataset? 

Thanks,
Aalisha

**Comment by AshwinSankar17** [comment]
Hi Aalisha,

Thank you for your kind words and interest in our work! We currently do not have a separate repository for the trained TTS model. However, we're more than happy to assist anyone interested in starting their own training using the provided dataset and code.

Unfortunately, we cannot release the trained model at this time, as it demonstrates strong zero-shot speaker adaptation capabilities, which pose a potential risk of misuse. We are exploring options to provide access through an API with watermarking in the future, but nothing is finalized yet.

We appreciate your understanding and support!

Best,
Ashwin
