### ISSUE TITLE
Dataset download link broken and training code availability

### ISSUE THREAD

**Issue by harveenchadha** [AI4Bharat/IndicVoices-R#4]
Hi,

Just saw that the dataset link is broken: 
<img width="514" alt="Screenshot 2024-09-17 at 3 32 46 AM" src="https://github.com/user-attachments/assets/b0ecea49-5371-47e9-98e0-ac422598b771">

Also in the paper it is mentioned that the dataset along with code will be available, when can we expect the training code to be available?

**Comment by AshwinSankar17** [comment]
Hello, please follow these links for the resources:
   1. **Dataset:** https://ai4bharat.iitm.ac.in/datasets/IndicVoices-R
   2. **Code:** https://github.com/jasonppy/voicecraft/

**Comment by AshwinSankar17** [comment]
Updated README to reflect changes.
