### ISSUE TITLE
Finetuning & Testing scripts for Voicecraft

### ISSUE THREAD

**Issue by dhruvek** [AI4Bharat/IndicVoices-R#8]
Could you provide the training and testing scripts on voicecraft. Library used to adopt graphemes in the tts system.  I would like to increase the tokenizer for additional vocab data. Awaiting your response @AshwinSankar17 and Team

**Comment by svp19** [comment]
You may find the scripts in the latest [commit](https://github.com/AI4Bharat/IndicVoices-R/commit/f066c09ca23e6ceb8bfe3b9c396632c8ee687dc1).

Thanks for showing interest in our work.

**Comment by dhruvek** [comment]
Thank you for the support.
